### ISSUE TITLE
CaImAn 2023 Roadmap

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1142]
# Caiman Roadmap: August 2023 - August 2024
Our goals with Caiman naturally fall into three general categories:

- **Usability** – make Caiman's current feature base easier to use. 
- **Improvements** – improve or expand on Caiman's current feature base.
- **Community**: improve the quality of user experience, and increase base of users/contributors.

If you would like to get involved with any of the efforts in this roadmap, or have new ideas about how we can attain the above goals, please reach out by replying to this issue. This is an evolving document: check back to see how things are going, and if we have added any new goals. 

## Usability
Caiman already has many great features that we can do a better job bringing to existing and future users. Our roadmap for this:

- [ ] Update readme  [in progress]   
  - [X] Simplify install instructions (quickstart guide)    
  - [X] Add table of use cases with links to notebooks.    
  - [ ] Make caimanmanager usage the same across platforms.
  - [ ] Buttons: percent coverage, percent passing (see section on Improvements)    
- [ ] Rework CNMF demo notebook: `demo_notebook.ipynb` [in progress]
  - [ ] In general, simplify and make more beginner-friendly.
  - [ ] Discuss file types we can handle
  - [ ] Better address how to handle your own data.
  - [ ] Show how to iteratively search parameter space
  - [ ] Discuss loading estimates that have been saved
  - [ ] Add colab link
- [ ] Once `demo_notebook.ipynb` is done, use as template for others:
  - [ ] CNMFE demo
  - [ ] Motion correction demo
- [ ] Update documentation  
  - [ ] Docs are not rendering properly: fix (issue #997)
  - [ ] Update docs theme 
  - [ ] Update so docs are written in md instead of rst
  - [ ] Update docs: some are outdated or erroneous (gSiz)

## Improvements
While Caiman's current feature set is a strength, our goal is that it continuously evolve and improve. Our roadmap for this: 

- [ ] Add functionality to save estimates as csv (#1086).
- [ ] Get subidx parameter working with temporal cropping (issue #1106)
- [ ] Get rid of all pylab imports (good beginner issue)
- [ ] Add synthetic data generator class or function.
- [ ] Check number of frames for motion correction, with useful error messaging (#1036)
- [ ] Save to Pynapple format to work with Pynapple package (#1087).
- [ ] Refactor greedy initialization
  - [ ] Break up complex functions/methods into simple functions/methods
  - [ ] That are well-documented
  - [ ] And tested
  - [ ] When done, evaluate process and pick next pain point to refactor.
- [ ] Plan how to handle Tensorflow (issue #1126)
- [ ] Plan how to divide Caiman into caiman-core (for core estimator algorithms), and the rest (e.g., visualization). 

## Community
Caiman is made for its users. We need to consistently put in effort to improve the experience of our current user base, and ideally increase the number of users and contributors (from issue-raiser to maintainer). Our roadmap for this:

- [X] Issues and PRs
  - [X] Add more clear labeling systsem at github.
  - [X] Institute new policy: label and reply within 24 business hours (especilly PRs)!
- [X] Start quarterly Community Meetings to engage users.
- [X] Annual workshops to increase user base and help current users
- [ ] Post public roadmap to GitHub
- [ ] Create forum with threaded searchable discussions (move discussions to GitHub discussions)
- [ ] Create news/updates web page, with link on readme, for people to learn how to connect.
- [ ] Host a code sprint/hackathon at Flatiron Institute.
- [ ] Summer intern program (Summer 2024).
