### ISSUE TITLE
Handle warnings about upcoming deprecations

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1303]
Turned off warnings and checked for upcoming deprecations. Most of these are repeated many times in the different notebooks, just noting the warnings not where they are occurring in the code base:

- [ ] caiman\base\rois.py:56: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.   Coor = np.matrix([np.outer(np.ones(d2), np.arange(d1)).ravel(),

- [ ] caiman\utils\visualization.py:783: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead. (colormap = matplotlib.cm.get_cmap(cmap)  # choose any matplotlib colormap here)

- [ ]  Same warning given for line 157

- [ ] caiman\source_extraction\cnmf\spatial.py:844: DeprecationWarning: Please use `grey_dilation` from the `scipy.ndimage` namespace, the `scipy.ndimage.morphology` namespace is deprecated.  from scipy.ndimage.morphology import grey_dilation. (evaluate_components)
-
- [ ]  random.py:370: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version  return self.randrange(a, b+1)  (nb_view_components)

**Comment by EricThomson** [comment]
Couple of things:  most of these are very simple. `randrange()` deprecation is out of our control I just dumped stuff in here without thinking too much that's a Python standard library thing with v 3.10. The only one that will take some thinking/time is the `np.matrix()` one, and that is still not deprecated. Maybe better to handle that with the push to Numpy 2+. The others were all simple syntax changes. Testing them now.

**Comment by ethanbb** [comment]
> caiman\source_extraction\cnmf\spatial.py:844: DeprecationWarning: Please use grey_dilation from the scipy.ndimage namespace, the scipy.ndimage.morphology namespace is deprecated. from scipy.ndimage.morphology import grey_dilation. (evaluate_components)

I'm getting the same warning (repeated many many times) from line 955 of spatial.py (`construct_dilate_parallel`):

```python
from scipy.ndimage.morphology import generate_binary_structure, iterate_structure, grey_dilation
```

Since these are now imported at the top level, this line can just be removed, right?

**Comment by pgunn** [comment]
@ethanbb Ah, yes. Good spot. I've been trying to remove non-toplevel imports when I find them.

You want to do it or shall I?

**Comment by ethanbb** [comment]
So actually there is this comment in the same file: 

https://github.com/flatironinstitute/CaImAn/blame/bb55800806f0898592d79dcc705a0b53ccd01ec3/caiman/source_extraction/cnmf/spatial.py#L355-L359

which seems to imply that the local imports are needed for ipyparallel or multiprocessing workers. But I don't think that's true; anything defined at the module level, including imports, should be accessible to the workers regardless of how they are launched, right?

**Comment by pgunn** [comment]
Closing this; we've fixed a number of deprecations since this was opened.

**Comment by ethanbb** [comment]
So I'm looking at the main branch and I still see those local imports in `spatial.py` including the one causing tons of warnings. Obviously not a huge priority, but can we deal with this or just keep the issue open? I am fairly confident the local imports aren't needed, so I could just delete them and do some tests including multiprocessing?

**Comment by pgunn** [comment]
By local imports you mean within function bodies? We definitely should get rid of those if we can; I thought I had cleared out most of the warnings though, unless you're running a more recent version of python or other packages that are emitting more.

Let's open a new, more specific issue (unless you just want to take a shot at the issue directly).

**Comment by ethanbb** [comment]
Yeah it's just this one:

```
caiman\source_extraction\cnmf\spatial.py:844: DeprecationWarning: Please use grey_dilation from the scipy.ndimage namespace, the scipy.ndimage.morphology namespace is deprecated. from scipy.ndimage.morphology import grey_dilation. (evaluate_components)
```

Maybe it depends on the specific version of scipy? I am on 1.15.2. I can open another issue though.

**Comment by pgunn** [comment]
It might; actually, I'll just adjust the imports in dev; it should be a very safe change.
